version: '3'
services:
  flyway:
    image: flyway/flyway:10
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/flyway.conf:/flyway/conf/flyway.config
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=pass
    - POSTGRES_DB=chordanalyzr

  data-generator:
    build:
      context: ./data-generator
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=chordanalyzr
      - DB_USER=postgres
      - DB_PASSWORD=pass
      - OUTPUT_DIR=/output
    volumes:
      - ./frontend/public/data:/output
    depends_on:
      - flyway
    restart: "no"  # Run once and exit

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - flyway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chordanalyzr
      - SPRING_DATASOURCE_DB=chordanalyzr
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - data-generator  # Ensure data is generated before frontend starts
    environment:
      - VITE_USE_STATIC_DATA=true  # Flag to use static data by default
      - VITE_API_BASE_URL=http://localhost:8080