// Package store defines the data types the API serves and the storage
// interface the service layer depends on. JSON field names match the
// OpenAPI spec the frontend's client is generated from.
package store

import "context"

type Mode struct {
	ID   int64  `json:"id" db:"id"`
	Name string `json:"name" db:"name"`
}

type ScaleNote struct {
	SeqNote  int64  `json:"seqNote" db:"seq_note"`
	NoteName string `json:"noteName" db:"note_name"`
}

// ModeScaleChord is one row of mode_scale_chord_relation_view. Pointers mark
// columns that can be NULL in the view (left joins / aggregates).
type ModeScaleChord struct {
	ModeID                 int64   `json:"modeId" db:"mode_id"`
	ChordTypeID            int64   `json:"chordTypeId" db:"chord_type_id"`
	ChordNote              int64   `json:"chordNote" db:"chord_note"`
	KeyNote                int64   `json:"keyNote" db:"key_note"`
	Mode                   string  `json:"mode" db:"mode"`
	KeyName                string  `json:"keyName" db:"key_name"`
	ChordNoteName          *string `json:"chordNoteName" db:"chord_note_name"`
	ChordName              *string `json:"chordName" db:"chord_name"`
	ModeNotes              []int64 `json:"modeNotes" db:"mode_notes"`
	ChordNotes             *string `json:"chordNotes" db:"chord_notes"`
	ChordNoteNames         *string `json:"chordNoteNames" db:"chord_note_names"`
	ModeChordNoteDiff      []int64 `json:"modeChordNoteDiff" db:"mode_chord_note_diff"`
	ModeChordNoteDiffCount int64   `json:"modeChordNoteDiffCount" db:"mode_chord_note_diff_count"`
}

// ProgressionStep is one chord of a progression generated by
// fn_smooth_progression (R__voice_leading.sql).
type ProgressionStep struct {
	// ProgressionID groups the steps of one progression when several are
	// requested; 1 is the best-scoring result.
	ProgressionID int32 `json:"progressionId" db:"progression_id"`
	// Step is the 1-based position of this chord in the progression.
	Step int32 `json:"step" db:"step"`
	// Chord name, e.g. "Cmaj7".
	Chord string `json:"chord" db:"chord"`
	// VLFromPrev is the voice-leading distance from the previous chord
	// (0 for the first step).
	VLFromPrev int32 `json:"vlFromPrev" db:"vl_from_prev"`
	// TotalCost is the total voice-leading cost of this step's progression.
	TotalCost int32 `json:"totalCost" db:"total_cost"`
}

// Pin is a chord the progression must contain. Position is the 1-based step
// it is fixed at, or 0 to let the search place it wherever it fits best.
type Pin struct {
	Chord    string
	Position int
}

// RequiredNote is a note the chord at a given step must contain -- e.g. a
// melody note to reharmonize under. Position is the 1-based step; the SQL
// function drops entries at step 1 (the start chord) or out of range.
type RequiredNote struct {
	Note     string
	Position int
}

// BassNote is a note that must sound in the bass at a given step: the chord
// there is voiced over it (a slash chord when it isn't the root). Position
// is the 1-based step; the SQL function drops entries at step 1 (the start
// chord) or out of range.
type BassNote struct {
	Note     string
	Position int
}

type Store interface {
	Modes(ctx context.Context) ([]Mode, error)
	ScaleNotes(ctx context.Context, mode, key string) ([]ScaleNote, error)
	ChordsByModeKey(ctx context.Context, mode, key string) ([]ModeScaleChord, error)
	SmoothProgression(
		ctx context.Context,
		mode, key, startChord string,
		length int,
		randomness float64,
		extraNotes []string,
		rootWeight, slashWeight float64,
		pins []Pin,
		required []RequiredNote,
		bass []BassNote,
		minNotes, maxNotes, resultCount int,
		colorWeight float64,
		colorDevices []string,
		ending string,
		loopWeight float64,
		// brightness is -1..+1; 0 means "off", like every other weight knob
		// here, even though the SQL function's own NULL sentinel can
		// distinguish "off" from "explicitly targeting neutral brightness" --
		// a distinction not worth a pointer type at this layer.
		brightness float64,
		avoidNotes []string,
		motionProfile string,
		revisitWeight float64,
	) ([]ProgressionStep, error)
}
